SELECT PDD.DESCRIPTION 'indirim adı',
       TH.TRANS_DATE 'tarih',
       P.NUM AS 'yazar kasa',
       S.DESCRIPTION AS 'MAGAZA',
       U.NAME AS 'KASIYER',
       TH.RECEIPT_BARCODE AS barkod,
       TS.CODE,
       TS.DESCRIPTION AS 'ürün AÇIKLAMA',
       FORMAT(TH.GROSS_TOTAL, 'N2') 'belge tutarı',
       FORMAT(TS.UNIT_PRICE, 'N2') 'urun fiyatı',
       FORMAT(TD.AMOUNT, 'N2') 'indirim tutarı',
       FORMAT((TS.UNIT_PRICE - TD.AMOUNT), 'N2') AS 'indirilmiş fiyat'
FROM GENIUS3.TRANSACTION_HEADER AS TH
    INNER JOIN GENIUS3.TRANSACTION_DISCOUNT AS TD
        ON TH.ID = TD.FK_TRANSACTION_HEADER
    INNER JOIN GENIUS3.TRANSACTION_SALE AS TS
        ON TH.ID = TS.FK_TRANSACTION_HEADER /*TS.LINE_NO = TD.PARENT_LINE */
    INNER JOIN GENIUS3.PROMO_DEFINED_DISCOUNT AS PDD
        ON TD.PARAMETER_3 = PDD.NUM
    INNER JOIN GENIUS3.STORE AS S
        ON TH.FK_STORE = S.ID
    INNER JOIN GENIUS3.POS AS P
        ON TH.FK_POS = P.ID
    INNER JOIN GENIUS3.USERS AS U
        ON TH.FK_USER = U.ID
    INNER JOIN GENIUS3.[DOCUMENT] AS DOC
        ON TH.PTYPE = DOC.NUM
WHERE (TD.DISCOUNT_TYPE = 6)
      AND (DOC.PRICE_FLAG <> 0)
      AND (TH.STATUS = 0)
      AND ((TS.LINE_NO = TD.PARENT_LINE))
      AND TH.TRANS_DATE >= 'baslangic Tarihi'
